export const initialMedicalCases = [
  {
    id: 1,
    title: 'Caso Complexo de Rinoplastia Revisional',
    specialty: 'Rinoplastia',
    submittedBy: 'Dr. Ana Couto',
    status: 'Em Análise' as const,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'surgery nose',
    analysis: null,
    imageCount: 3,
    videoCount: 1,
  },
  {
    id: 2,
    title: 'Mamoplastia de Aumento com Prótese de Silicone',
    specialty: 'Mamoplastia',
    submittedBy: 'Dr. Lucas Martins',
    status: 'Aprovado' as const,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'surgery breast',
    analysis: 'O planejamento pré-operatório foi excelente, com boa escolha do implante. A técnica de inserção dual-plane garantiu um resultado natural e simétrico. Recomendo atenção ao acompanhamento pós-operatório para monitorar a contratura capsular.',
    imageCount: 5,
    videoCount: 0,
  },
  {
    id: 3,
    title: 'Blefaroplastia Superior e Inferior',
    specialty: 'Blefaroplastia',
    submittedBy: 'Dr. Sofia Ferreira',
    status: 'Aprovado' as const,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'surgery eye',
    analysis: null,
    imageCount: 2,
    videoCount: 0,
  },
  {
    id: 4,
    title: 'Lifting Facial Completo (Ritidoplastia)',
    specialty: 'Lifting',
    submittedBy: 'Dr. Carlos Andrade',
    status: 'Em Análise' as const,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'surgery face',
    analysis: null,
    imageCount: 4,
    videoCount: 2,
  },
  {
    id: 5,
    title: 'Rinoplastia Estruturada Pós-Trauma',
    specialty: 'Rinoplastia',
    submittedBy: 'Dr. Gabriela Lima',
    status: 'Aprovado' as const,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'rhinoplasty surgery',
    analysis: 'Excelente reconstrução da estrutura nasal. O uso de enxertos cartilaginosos foi preciso e garantiu a funcionalidade respiratória. As proporções faciais foram respeitadas, resultando em um perfil harmonioso.',
    imageCount: 6,
    videoCount: 1,
  },
  {
    id: 6,
    title: 'Reconstrução Mamária Pós-Mastectomia',
    specialty: 'Mamoplastia',
    submittedBy: 'Dr. Pedro Almeida',
    status: 'Requer Revisão' as const,
    imageUrl: 'https://placehold.co/600x400',
    imageHint: 'mastectomy reconstruction',
    analysis: 'A técnica de retalho DIEP foi bem executada, mas a simetrização com a mama contralateral pode ser aprimorada em um segundo tempo cirúrgico. Sugiro avaliação do complexo areolopapilar.',
    imageCount: 3,
    videoCount: 1,
  },
];

export const caseDetails = {
    id: 1,
    title: 'Caso Complexo de Rinoplastia Revisional',
    submittedBy: 'Dr. Ana Couto',
    submittedAt: '2024-07-28T10:00:00Z',
    specialty: 'Rinoplastia',
    status: 'Aprovado',
    analysis: 'O planejamento pré-operatório foi excelente, com boa escolha do implante. A técnica de inserção dual-plane garantiu um resultado natural e simétrico. Recomendo atenção ao acompanhamento pós-operatório para monitorar a contratura capsular.',
};

export const timelineEvents = [
    { type: 'submission', user: 'Dr. Ana Couto', timestamp: '2024-07-28T10:00:00Z', description: 'enviou o caso para análise.' },
    { type: 'analysis', user: 'Dr. Genkit', timestamp: '2024-07-28T10:05:00Z', description: 'concluiu a análise inicial.' },
    { type: 'comment', user: 'Dr. Lucas Martins', timestamp: '2024-07-28T14:30:00Z', description: 'comentou: "Excelente caso. A abordagem com enxerto de costela parece a mais indicada. Qual a sua opinião sobre o uso de fáscia temporal?"' },
    { type: 'comment', user: 'Dr. Sofia Ferreira', timestamp: '2024-07-29T09:15:00Z', description: 'comentou: "Concordo com o Dr. Lucas. A fáscia temporal pode ser uma ótima opção para camuflagem e refinamento da ponta nasal."' },
    { type: 'approval', user: 'Admin', timestamp: '2024-07-29T18:00:00Z', description: 'aprovou o caso para o acervo.' },
];
